# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='likes_books_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_users', to='likes_books_app.User'),
        ),
    ]
